services:
  slack-mcp:
    build: .
    container_name: slack-mcp
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_TEAM_ID=${SLACK_TEAM_ID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true
    tty: true
    networks:
      - mcp-network

networks:
  mcp-network:
    name: slack-mcp-network
    driver: bridge
